name: Validate Pull Request

on: 
  push:
      branches: 
        - main

jobs:
  on_content_change:
    runs-on: ubuntu-latest
    name: On Content Change

    steps:
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10

      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done
          

