name: Validate Pull Request

on: 
  push:
      branches: 
        - master

jobs:
  on_content_change:
    runs-on: ubuntu-latest
    name: On Content Change

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10

      - name: List all modified files
        run: |
          for file in "${{ steps.changed-files.outputs.all_modified_files }}"; do
            echo "$file was modified"
          done
          

