name: Validate Pull Request

on: 
  push:
      branches: 
        - master

jobs:
  on_content_change:
    runs-on: ubuntu-latest
    name: On Content Change

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 
      
      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v10

      - name: List all modified files
        id: has-modified
        run: |
               echo "${{ steps.changed-files.outputs.all_modified_files }}" | ./.github/workflows/scripts/diff.sh "content/"; echo "$?"

      - name: Content is modified
        if: '${{ steps.has-modified.outputs.has-modified.has-modified }} == 0'
        run: |
          echo "sabes habibs"


